# vim: filetype=yaml.ansible

- hosts: main
  roles:
    # - update
    - security
    # - role: artis3n.tailscale
    #   vars:
    #     tailscale_authkey: "{{ lookup('env', 'TAILSCALE_AUTH_KEY') }}"
