- name: upload fail2ban config
  ansible.builtin.copy:
    src: files/jail.local
    dest: /etc/fail2ban/jail.local
  become: yes
  notify: restart fail2ban

- name: enable fail2ban
  ansible.builtin.systemd:
    name: fail2ban
    enabled: true
    state: started
  become: yes
