- name: Accept SSH on port 22
  ansible.builtin.iptables:
    chain: INPUT
    protocol: tcp
    destination_port: 22
    jump: ACCEPT
  become: yes

- name: Allow http and https
  ansible.builtin.iptables:
    chain: INPUT
    protocol: tcp
    destination_ports:
      - 80
      - 443
    jump: ACCEPT
  become: yes

# - name: Allow everything on tailscale0
#   ansible.builtin.iptables:
#     chain: INPUT
#     in_interface: tailscale0
#     protocol: all
#     jump: ACCEPT
#   become: yes

- name: DROP everything
  ansible.builtin.iptables:
    chain: INPUT
    policy: DROP
    action: insert
  become: yes

- name: save iptables config
  community.general.iptables_state:
    state: saved
    path: /etc/iptables/iptables.rules
  become: yes
