- name: debian keyrings
  ansible.builtin.apt:
    name:
      - debian-keyring
      - debian-archive-keyring
      - apt-transport-https
    state: latest
  become: yes

- name: check if caddy repo exist
  ansible.builtin.stat:
    path: /etc/apt/sources.list.d/caddy-stable.list
  register: repo_exists

- name: add caddy repos
  ansible.builtin.shell: curl -1sLf 'https://dl.cloudsmith.io/public/caddy/stable/gpg.key' | sudo gpg --dearmor -o /usr/share/keyrings/caddy-stable-archive-keyring.gpg && curl -1sLf 'https://dl.cloudsmith.io/public/caddy/stable/debian.deb.txt' | sudo tee /etc/apt/sources.list.d/caddy-stable.list
  become: yes
  when: not repo_exists.stat.exists

- name: install caddy
  ansible.builtin.apt:
    name: caddy
    state: latest
    update_cache: true
  become: yes

- name: make sure caddy is running
  ansible.builtin.systemd:
    name: caddy
    state: started
    enabled: true
  become: yes

- name: create caddy sites directory
  ansible.builtin.file:
    path: /etc/caddy/sites
    state: directory
    mode: 644
  become: yes

- name: create Caddyfile
  ansible.builtin.template:
    src: files/Caddyfile
    dest: /etc/caddy/Caddyfile
    force: no
  vars:
    email: "{{ lookup('env', 'EMAIL') }}"
  become: yes
  notify: reload caddy
